tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "railwaycat/emacsmacport"

brew "bat"
brew "curl"
brew "emacs-mac", args: ["with-modern-icon", "with-imagemagick", "with-starter"]
brew "exa"
brew "git"
brew "gnu-time"
brew "grpcurl"
brew "htop"
brew "hyperfine"
brew "libpq", link: true
brew "mold"
brew "openssl@3"
brew "starship"
brew "telnet"
brew "tmux"
brew "tmux-mem-cpu-load"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"

cask_args appdir: "/Applications", fontdir: "${HOME}/Library/Fonts"

cask "alacritty"
cask "deepl"
cask "docker"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "karabiner-elements"
cask "visual-studio-code"
