import = [
  "~/.config/alacritty/colors/base16-gruvbox-dark-hard.toml",
]

[font]
size = 14.0
normal = { family = "Iosevka Term SS09", style = "Extended" }
bold = { family = "Iosevka Term SS09", style = "Bold Extended" }
italic = { family = "Iosevka Term SS09", style = "Extended Italic" }
bold_italic = { family = "Iosevka Term SS09", style = "Bold Extended Italic" }

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "~Search"
mods = "Command"

[scrolling]
history = 0

[window]
decorations = "none"
opacity = 0.9
option_as_alt = "Both"
