import = [
  "~/.config/alacritty/colors/base16-tomorrow-night.toml",
]

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "~Search"
mods = "Command"

[scrolling]
history = 0

[window]
decorations = "none"
opacity = 0.9
option_as_alt = "Both"
