format = """
$jobs$time$hostname$username$directory\
[( \\($git_branch$git_commit$git_state$git_status\\))](fg:cyan)\
$character
"""
right_format = "$cmd_duration"
add_newline = false

[hostname]
ssh_only = true
trim_at = "."
style = "fg:bright-black"
format = "[$hostname@]($style)"

[username]
style_root = "fg:red bold"
style_user = "fg:blue"
format = "[$user]($style)"
show_always = true

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[::](fg:bright-black)[$path]($style)"
style = "fg:cyan"
truncation_symbol = "…/"
repo_root_style = "fg:cyan"
repo_root_format = "[::](fg:bright-black)[$repo_root]($repo_root_style)[$path]($style)"

[character]
format = " $symbol "
success_symbol = "[|](fg:red)"
error_symbol = "[¦](fg:red)"

[cmd_duration]
min_time = 1_000
format = "[\\($duration\\)]($style)"
style = "bright-black"

[git_branch]
format = "$branch"

[git_status]
format = "( $all_status$ahead_behind)"

[time]
disabled = false
time_format = "%R"
style = "fg:bright-black"
format = "[\\[$time\\]]($style) "
