name: Make dotfiles

on:
  push:
    branches:
      - main

jobs:
  make:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make dotfiles
        run: DOTFILES_HOME=${{ github.workspace }} make
